### ISSUE TITLE
Incompatible with Modsmod

### ISSUE THREAD

**Issue by Pandaptable** [Gaming32/mod-loading-screen#32]
https://modrinth.com/mod/modsmod

Mod loading screen instantly closes when using it

**Comment by Gaming32** [comment]
It appears to be loading before MLS and loading classes that MLS needs to transform. Should be a fairly easy fix, as I just need to change MLS to retransform all loaded classes it cares about, instead of just one of them, as it does currently.

**Comment by Gaming32** [comment]
Fixed in 1.0.5

**Comment by Pandaptable** [comment]
I seem to be still getting crashes..? https://mclo.gs/vsw40ZY
not gonna lie I made this issue as a joke but despite the fix there seems to be issues still (done on an instance with nothing but the required mods)
